title: Tom Leskin
description: Journalist turned developer.

url: http://tleskin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Resume
   url: /resume
 - title: Recommendations
   url: /rec
 - title: About
   url: /about

social:
   github: tleskin
   twitter: tomleskin
   facebook: tomleskin
   email: tleskin@gmail.com

google_analytics: "UA-58263416-1"

gems: [jekyll-paginate, pygments.rb]
