title: Tom Leskin
description: American journalist turned software developer.

url: http://tleskin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: tleskin
   twitter: tomleskin
   facebook: tomleskin
   email: tleskin@gmail.com

google_analytics: "UA-58263416-1"
